/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiLink: typeof import('./theme/components/ApiLink.vue')['default']
    copy: typeof import('./theme/components/ReactiveVscode2.vue')['default']
    ExampleContainer: typeof import('./theme/components/ExampleContainer.vue')['default']
    ExampleFunctions: typeof import('./theme/components/ExampleFunctions.vue')['default']
    FunctionBadge: typeof import('./theme/components/FunctionBadge.vue')['default']
    FunctionInfo: typeof import('./theme/components/FunctionInfo.vue')['default']
    FunctionsList: typeof import('./theme/components/FunctionsList.vue')['default']
    NonProprietary: typeof import('./theme/components/NonProprietary.vue')['default']
    ReactiveVscode: typeof import('./theme/components/ReactiveVscode.vue')['default']
    ReactiveVscode2: typeof import('./theme/components/ReactiveVscode2.vue')['default']
  }
}
