/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FunctionBadge: typeof import('./theme/components/FunctionBadge.vue')['default']
    FunctionsList: typeof import('./theme/components/FunctionsList.vue')['default']
  }
}
