# Continuous Releases provided by https://pkg.pr.new
name: CR (Continuous Releases)
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm --filter './packages/*' build

      - run: pnpx pkg-pr-new publish './packages/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
